Repository AY1920S1-CS2113-T14-1/main, pull requests merged in 2019-10, with the labels that each got.

#82 Add Coveralls
  .travis.yml
  build.gradle
Labels: status.Ongoing

#101 Created initial duke objects
  src/main/java/duke/task/DukeData.java
  src/main/java/duke/task/DukeObject.java
  src/main/java/duke/task/Evidence.java
  src/main/java/duke/task/Impression.java
  src/main/java/duke/task/Patient.java
  src/main/java/duke/task/Treatment.java
Labels: component.Model

#138 GsonStorage and GsonStorageTest made compatible with the PatientMap class
  src/main/java/duke/DukeCore.java
  src/main/java/duke/data/GsonStorage.java
  src/main/java/duke/data/PatientMap.java
  src/test/java/GsonStorageTest.java
Labels: component.Model

#147 Finalise UI Component
  src/main/java/duke/DukeCore.java
  src/main/java/duke/command/Ui.java
  src/main/java/duke/exception/DukeFatalException.java
  src/main/java/duke/gui/CommandWindow.java
  src/main/java/duke/gui/Context.java
  src/main/java/duke/gui/DialogBox.java
  src/main/java/duke/gui/Gui.java
  src/main/java/duke/gui/HomeWindow.java
  src/main/java/duke/gui/MainWindow.java
  src/main/java/duke/gui/Message.java
  src/main/java/duke/gui/PatientWindow.java
  src/main/java/duke/gui/Ui.java
  src/main/java/duke/gui/UiComponent.java
  src/main/java/duke/gui/UiManager.java
  src/main/java/duke/ui/CommandWindow.java
  src/main/java/duke/ui/HomeWindow.java
  src/main/java/duke/ui/MainWindow.java
  src/main/java/duke/ui/MessageBox.java
  src/main/java/duke/ui/PatientCard.java
  src/main/java/duke/ui/PatientWindow.java
  src/main/java/duke/ui/Ui.java
  src/main/java/duke/ui/UiElement.java
  src/main/java/duke/ui/UiManager.java
  src/main/resources/images/duke.png
  src/main/resources/images/user.png
  src/main/resources/view/CommandWindow.fxml
  src/main/resources/view/HomeWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MessageBox.fxml
  src/main/resources/view/PatientWindow.fxml
  src/test/java/CommandTest.java
Labels: component.UI

#148 Add ability to switch between UI contexts
  src/main/java/duke/DukeCore.java
  src/main/java/duke/command/Executor.java
  src/main/java/duke/ui/CommandWindow.java
  src/main/java/duke/ui/HomeWindow.java
  src/main/java/duke/ui/MainWindow.java
  src/main/java/duke/ui/UiContext.java
Labels: component.UI

#149 Update Developer Guide
  docs/DeveloperGuide.adoc
Labels: component.ProjectMgmt

#152 Patient: Convert primitive int to Object Integer
  src/main/java/duke/data/Patient.java
  src/test/java/GsonStorageTest.java
Labels: component.Model

#157 Add documentation for Autocomplete feature
  docs/DeveloperGuide.adoc
  docs/images/AutoCompleteActivityDiagram.png
  docs/images/crop_ss.png
Labels: component.ProjectMgmt

#158 Release v1.2.1
  build.gradle
  src/main/java/duke/DukeCore.java
  src/main/java/duke/Launcher.java
  text-ui-test/EXPECTED.txt
  text-ui-test/input.txt
  text-ui-test/runtest.bat
  text-ui-test/runtest.sh
Labels: component.ProjectMgmt

#160 Complete toString methods and find methods
  src/main/java/duke/data/DukeData.java
  src/main/java/duke/data/DukeObject.java
  src/main/java/duke/data/Evidence.java
  src/main/java/duke/data/Impression.java
  src/main/java/duke/data/Investigation.java
  src/main/java/duke/data/Medicine.java
  src/main/java/duke/data/Observation.java
  src/main/java/duke/data/Patient.java
  src/main/java/duke/data/PatientMap.java
  src/main/java/duke/data/Plan.java
  src/main/java/duke/data/Result.java
  src/main/java/duke/data/Treatment.java
  src/test/java/GsonStorageTest.java
Labels: component.Model, priority.Medium

#163 Relocate Context enum
  src/main/java/duke/command/Commands.java
  src/main/java/duke/command/Parser.java
  src/main/java/duke/ui/Context.java
  src/main/java/duke/ui/MainWindow.java
  src/main/java/duke/ui/UiContext.java
  src/test/java/ParserTest.java
  src/test/java/mocks/TestCommands.java
Labels: component.UI

#169 Complete base version of autocomplete feature
  src/main/java/duke/ui/AutoCompleteTextField.java
  src/main/java/duke/ui/CommandWindow.java
  src/main/java/duke/ui/Context.java
  src/main/resources/view/CommandWindow.fxml
Labels: type.Task

#178 Open command
  src/main/java/duke/DukeCore.java
  src/main/java/duke/command/Commands.java
  src/main/java/duke/command/HomeOpenCommand.java
  src/main/java/duke/command/HomeOpenSpec.java
  src/main/java/duke/data/GsonStorage.java
  src/main/java/duke/data/PatientMap.java
  src/main/java/duke/ui/HomeWindow.java
  src/main/java/duke/ui/MainWindow.java
  src/main/java/duke/ui/PatientWindow.java
  src/main/java/duke/ui/UiContext.java
  src/main/resources/images/address.png
  src/main/resources/images/age.png
  src/main/resources/images/aid.png
  src/main/resources/images/allergies.png
  src/main/resources/images/details.png
  src/main/resources/images/duke.png
  src/main/resources/images/follow-ups.png
  src/main/resources/images/heart.png
  src/main/resources/images/height.png
  src/main/resources/images/impressions.png
  src/main/resources/images/issues.png
  src/main/resources/images/patient.png
  src/main/resources/images/phone.png
  src/main/resources/images/user.png
  src/main/resources/images/ward.png
  src/main/resources/images/weight.png
  src/main/resources/images/wip.png
  src/main/resources/view/HomeWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PatientCard.fxml
  src/main/resources/view/PatientWindow.fxml
Labels: type.Task

#175 Resolve Coveralls bug
  .travis.yml
  README.md
  build.gradle
  gradle.properties
Labels: type.Bug, type.Task

#179 Add simplifed class diagram for UI component
  docs/images/plantuml/ui.png
Labels: component.ProjectMgmt

#200 Create Impression Panel in [Patient] context
  src/main/java/duke/command/PatientNewCommand.java
  src/main/java/duke/data/Patient.java
  src/main/java/duke/data/PatientMap.java
  src/main/java/duke/ui/HomeWindow.java
  src/main/java/duke/ui/ImpressionCard.java
  src/main/java/duke/ui/MainWindow.java
  src/main/java/duke/ui/PatientWindow.java
  src/main/resources/images/impression_critical.png
  src/main/resources/images/impression_follow-up.png
  src/main/resources/images/impression_name.png
  src/main/resources/images/impressions.png
  src/main/resources/view/ImpressionCard.fxml
  src/main/resources/view/PatientCard.fxml
  src/main/resources/view/PatientWindow.fxml
Labels: component.UI

#201 Create [primary] command in [Patient] context
  src/main/java/duke/command/Commands.java
  src/main/java/duke/command/PatientEditCommand.java
  src/main/java/duke/command/PatientEditSpec.java
  src/main/java/duke/command/PatientPrimaryCommand.java
  src/main/java/duke/command/PatientPrimarySpec.java
  src/main/java/duke/data/Patient.java
  src/main/java/duke/data/PatientMap.java
  src/main/java/duke/ui/ImpressionCard.java
  src/main/java/duke/ui/PatientCard.java
  src/main/java/duke/ui/PatientWindow.java
  src/main/resources/view/ImpressionCard.fxml
  src/main/resources/view/PatientWindow.fxml
Labels: type.Bug, type.Task

#204 Create [History] command in [Patient] context
  src/main/java/duke/command/Commands.java
  src/main/java/duke/command/PatientEditCommand.java
  src/main/java/duke/command/PatientHistoryCommand.java
  src/main/java/duke/command/PatientHistorySpec.java
  src/main/java/duke/data/Patient.java
  src/main/java/duke/ui/PatientWindow.java
Labels: type.Task

#217 Create [up] command
  src/main/java/duke/command/Commands.java
  src/main/java/duke/command/UpCommand.java
  src/main/java/duke/command/UpSpec.java
  src/main/java/duke/ui/CommandWindow.java
  src/main/java/duke/ui/ImpressionCard.java
  src/main/java/duke/ui/InputHistoryWindow.java
  src/main/java/duke/ui/PatientCard.java
  src/main/java/duke/ui/PatientWindow.java
  src/main/java/duke/ui/UiContext.java
Labels: type.Task

#218 Update allergies panel as patient allergies are updated
  src/main/java/duke/data/Patient.java
  src/main/java/duke/ui/CommandWindow.java
  src/main/java/duke/ui/PatientWindow.java
Labels: type.Task

#220 Create [edit] command in [Patient] context
  docs/UserGuide.adoc
  src/main/java/duke/command/HomeDischargeCommand.java
  src/main/java/duke/command/HomeNewCommand.java
  src/main/java/duke/command/HomeOpenCommand.java
  src/main/java/duke/command/PatientDeleteCommand.java
  src/main/java/duke/command/PatientEditCommand.java
  src/main/java/duke/command/PatientEditSpec.java
  src/main/java/duke/command/PatientHistoryCommand.java
  src/main/java/duke/command/PatientPrimaryCommand.java
  src/main/java/duke/data/Patient.java
  src/main/java/duke/ui/HomeWindow.java
  src/main/java/duke/ui/MainWindow.java
  src/main/java/duke/ui/PatientCard.java
  src/main/java/duke/ui/PatientWindow.java
  src/main/resources/view/PatientWindow.fxml
  src/test/java/GsonStorageTest.java
Labels: type.Task

#227 Create [open] command for the [Impression] context
  src/main/java/duke/command/Commands.java
  src/main/java/duke/command/PatientEditCommand.java
  src/main/java/duke/command/PatientEditSpec.java
  src/main/java/duke/command/PatientOpenCommand.java
  src/main/java/duke/command/PatientOpenSpec.java
  src/main/java/duke/ui/PatientWindow.java
  src/main/java/duke/ui/UiContext.java
Labels: type.Task

#233 Find command home
  src/main/java/duke/command/Commands.java
  src/main/java/duke/command/HomeFindCommand.java
  src/main/java/duke/command/HomeFindSpec.java
  src/main/java/duke/command/PatientFindCommand.java
  src/main/java/duke/data/PatientMap.java
Labels: type.Bug

#241 Impression find
  src/main/java/duke/command/Commands.java
  src/main/java/duke/command/impression/ImpressionFindCommand.java
  src/main/java/duke/command/impression/ImpressionFindSpec.java
Labels: priority.High

#244 Gson storage bug
  settings.gradle
  src/main/java/duke/data/EvidenceAdaptor.java
  src/main/java/duke/data/GsonStorage.java
  src/main/java/duke/data/Plan.java
  src/main/java/duke/data/TreatmentAdaptor.java
  src/main/java/duke/ui/ImpressionWindow.java
Labels: priority.Core, severity.High, type.Bug

#251 Finalise Home Context
  docs/UserGuide.adoc
  src/main/java/duke/command/CommandHelpers.java
  src/main/java/duke/command/home/HomeDischargeAndReportSpec.java
  src/main/java/duke/command/home/HomeDischargeCommand.java
  src/main/java/duke/command/home/HomeFindCommand.java
  src/main/java/duke/command/home/HomeHelpCommand.java
  src/main/java/duke/command/home/HomeHelpSpec.java
  src/main/java/duke/command/home/HomeHistoryCommand.java
  src/main/java/duke/command/home/HomeHistorySpec.java
  src/main/java/duke/command/home/HomeNewCommand.java
  src/main/java/duke/command/home/HomeNewSpec.java
  src/main/java/duke/command/home/HomeOpenCommand.java
  src/main/java/duke/command/home/HomeOpenSpec.java
Labels: component.ProjectMgmt, priority.High

#253 Search context
  src/main/java/duke/command/home/HomeFindCommand.java
  src/main/java/duke/command/impression/ImpressionFindCommand.java
  src/main/java/duke/command/patient/PatientFindCommand.java
  src/main/java/duke/data/Result.java
  src/main/java/duke/data/SearchResult.java
  src/main/java/duke/ui/UiStrings.java
  src/main/java/duke/ui/context/Context.java
  src/main/java/duke/ui/window/MainWindow.java
  src/main/java/duke/ui/window/SearchWindow.java
  src/main/resources/images/home.png
  src/main/resources/images/search.png
  src/main/resources/images/searchResults.png
  src/main/resources/view/SearchWindow.fxml
Labels: component.Model, component.UI, priority.Medium

#258 Revert User Guide
  docs/UserGuide.adoc
Labels: component.ProjectMgmt

#270 Bug fix
  src/main/java/duke/DukeCore.java
  src/main/java/duke/command/impression/ImpressionFindCommand.java
  src/main/java/duke/command/patient/PatientFindCommand.java
  src/main/java/duke/data/PatientMap.java
  src/main/java/duke/ui/window/MainWindow.java
Labels: severity.High, type.Bug
